<a href="https://colab.research.google.com/github/theysee/sberbank_reboot/blob/master/%D0%9F%D0%BE%D1%82%D0%BE%D0%BA_3_%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BA_%D0%B7%D0%B0%D0%BD%D1%8F%D1%82%D0%B8%D1%8E_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Практика



*   [Презентация](https://docs.google.com/presentation/d/1CE5hOVm2PBSDXA9sK7WtikFV8rUZlYwA9hc8vVh_tgY/edit?usp=sharing)
*   [master](https://colab.research.google.com/drive/1TeKcA6LIpFABRfBPWEz8VTWtZzRwDIhR)
*   [Дамп базы](https://drive.google.com/open?id=1RJx-1kh8az1OSQqnsDjCTWdzJBlDkjcB)

![схема базы](http://bdis.umeta.ru/db/db_course/labs/SQLpHTM/king.gif)


In [180]:
!pip install PyMySQL

In [181]:
!pip install pandas

In [0]:
import pymysql
import pandas as pd
# доступны student-ы от 0 до 49

DB_HOST = '89.223.95.235'
DB_USER = 'student_12'
DB_USER_PASSWORD = 'student_12'
DB_NAME = 'sample_db'

In [183]:
conn = pymysql.connect(DB_HOST, DB_USER, DB_USER_PASSWORD, DB_NAME)
pd.read_sql_query("SELECT * FROM employee", conn).head(5)

employee_id last_name first_name  ...  salary  commission  department_id
0         7369     smith       john  ...   800.0         NaN             20
1         7499     allen      kevin  ...  1600.0       300.0             30
2         7505     doyle       jean  ...  2850.0         NaN             13
3         7506    dennis       lynn  ...  2750.0         NaN             23
4         7507     baker     leslie  ...  2200.0         NaN             14

[5 rows x 10 columns]

### Задание 1
Выбрать коды всех городов, в которых расположены отделы фирмы.

In [184]:
pd.read_sql_query('''
  SELECT 
    DISTINCT
    Location_id AS Loc_ID 
  FROM 
    department
  ''', conn)

Loc_ID
0     122
1     123
2     124
3     167

### Задание 2
Для каждого сотрудника определить, какой процент по отношению к зарплате составляют его комиссионные.

In [185]:
pd.read_sql_query("""
  SELECT 
    employee_id, COALESCE(commission, 0)/salary * 100 AS Percent
  FROM 
    employee
  ORDER BY 
    percent DESC
  """, conn)

employee_id     Percent
0          7654  112.000000
1          7557   96.000000
2          7600   72.000000
3          7789   66.666667
4          7820   61.538462
5          7521   40.000000
6          7555   24.000000
7          7564   24.000000
8          7499   18.750000
9          7919    0.000000
10         7916    0.000000
11         7902    0.000000
12         7934    0.000000
13         7900    0.000000
14         7950    0.000000
15         7876    0.000000
16         7844    0.000000
17         7839    0.000000
18         7369    0.000000
19         7954    0.000000
20         7799    0.000000
21         7788    0.000000
22         7782    0.000000
23         7698    0.000000
24         7676    0.000000
25         7609    0.000000
26         7569    0.000000
27         7566    0.000000
28         7560    0.000000
29         7507    0.000000
30         7506    0.000000
31         7505    0.000000

### Задание 3
Вывести два инициала (с точками) и фамилии всех сотрудников, например:

In [186]:
pd.read_sql_query("""
  SELECT
    CONCAT(SUBSTR(first_name, 1, 1), '.') AS I1,
    CONCAT(middle_initial, '.') AS I2,
    last_name
  FROM
    employee
  """, conn)

I1  I2 last_name
0   j.  q.     smith
1   k.  j.     allen
2   j.  k.     doyle
3   l.  s.    dennis
4   l.  d.     baker
5   c.  d.      ward
6   d.  t.    peters
7   k.  p.      shaw
8   s.  s.    duncan
9   g.  j.     lange
10  t.  m.     jones
11  c.  l.   alberts
12  r.  y.    porter
13  r.  m.     lewis
14  k.  j.    martin
15  d.  d.   sommers
16  m.  s.     blake
17  c.  f.     clark
18  d.  t.     scott
19  l.  n.      west
20  m.  g.    fisher
21  p.  s.      ross
22  f.  a.      king
23  m.  a.    turner
24  d.  g.     adams
25  f.  s.     james
26  j.  d.      ford
27  g.  m.   roberts
28  m.  a.   douglas
29  b.  m.    miller
30  a.  b.    jensen
31  j.  t.    murray

### Задание 4
По каждой сделке вывести точную сумму сделки, сумму сделки, округленную в большую сторону, округленную в меньшую сторону, округленную по общепринятым правилами округления.

In [187]:
pd.read_sql_query('''
  SELECT 
    order_id,
    total AS 'Sum_deal',
    CEILING(total) AS 'Max_val',
    FLOOR(total) AS 'Min_val',
    ROUND(total) AS 'Avg_val'
  FROM 
    sales_order
''',conn)

order_id  Sum_deal  Max_val  Min_val  Avg_val
0        501     216.0      216      216    216.0
1        502     500.0      500      500    500.0
2        503    1876.0     1876     1876   1876.0
3        504    1434.7     1435     1434   1435.0
4        505     650.0      650      650    650.0
..       ...       ...      ...      ...      ...
95       617   46370.0    46370    46370  46370.0
96       618    3083.0     3083     3083   3083.0
97       619    1260.0     1260     1260   1260.0
98       620    4450.0     4450     4450   4450.0
99       621     730.0      730      730    730.0

[100 rows x 5 columns]

### Задание 5
Выбрать фамилии всех сотрудников, у которых комиссионные больше зарплаты.

In [188]:
pd.read_sql_query('''
  SELECT
    Last_name,
    commission,
    salary
  FROM
    Employee
  WHERE
    commission > salary
''',conn)

Last_name  commission  salary
0    martin      1400.0  1250.0

### Задание 6
Выбрать фамилии всех сотрудников, фамилии которых начинаются на букву 'S'.

In [189]:
pd.read_sql_query('''
  SELECT 
    * 
  FROM 
    Employee
  WHERE 
    last_name LIKE 'S%'
''',conn)

employee_id last_name first_name  ...  salary  commission  department_id
0         7369     smith       john  ...   800.0         NaN             20
1         7557      shaw      karen  ...  1250.0      1200.0             13
2         7676   sommers     denise  ...  1850.0         NaN             34
3         7788     scott     donald  ...  3000.0         NaN             20

[4 rows x 10 columns]

### Задание 7
Выбрать имена всех сотрудников, которые не являются менеджерами (job_id=671) и не работают в отделе SALES в NEW YORK (department_id=13).

In [190]:
pd.read_sql_query('''
  SELECT 
    first_name,
    last_name,
    department_id,
    job_id
  FROM 
    Employee
  WHERE 
    job_id LIKE '671' AND department_id NOT LIKE '13'
''',conn)

first_name last_name  department_id  job_id
0       lynn    dennis             23     671
1     leslie     baker             14     671
2      terry     jones             20     671
3      chris   alberts             12     671
4     marion     blake             30     671
5      carol     clark             10     671

### Задание 8
Выбрать фамилии всех сотрудников, у которых код должности 670 или 677 (CLERK или SALESPERSON).

In [191]:
#Ошибка в задании CLERK job_id = 667, SALESPERSON job_id 670

pd.read_sql_query('''
  SELECT 
    last_name,
    job_id
  FROM 
    Employee
  WHERE 
    job_id LIKE '667' OR job_id LIKE '670'
  ORDER BY
    job_id
''',conn)

last_name  job_id
0     murray     667
1     jensen     667
2     miller     667
3    douglas     667
4      james     667
5      adams     667
6      smith     667
7       west     670
8     turner     670
9       ross     670
10    martin     670
11    porter     670
12     lange     670
13    duncan     670
14      shaw     670
15    peters     670
16      ward     670
17     allen     670

### Задание 9
Выбрать всех сотрудников, имена которых состоят из 6 букв и начинаются на 'MAR'.

In [192]:
pd.read_sql_query('''
  SELECT 
    first_name,
    last_name
  FROM 
    Employee
  WHERE
    LENGTH(first_name) = '6' AND first_name LIKE 'Mar%' OR
    LENGTH(last_name) = '6' AND last_name LIKE 'Mar%'
''',conn)

first_name last_name
0    kenneth    martin
1     marion     blake

### Задание 10
Выбрать фамилии всех сотрудников, которые поступили на работу после 15 апреля 1985 года.

In [193]:
pd.read_sql_query('''
  SELECT 
    last_name,
    hire_date
  FROM 
    Employee
  WHERE
    hire_date >= '1985-04-15'
  ORDER BY
    hire_date
''',conn)

last_name  hire_date
0     porter 1985-04-15
1      lewis 1985-04-16
2    sommers 1985-04-19
3      blake 1985-05-01
4     dennis 1985-05-15
5     duncan 1985-05-31
6       ross 1985-06-01
7      lange 1985-06-01
8      clark 1985-06-09
9      baker 1985-06-10
10    turner 1985-09-08
11    martin 1985-09-28
12      king 1985-11-17
13     james 1985-12-03
14      ford 1985-12-03
15    miller 1986-01-23
16     scott 1986-12-09
17    fisher 1986-12-12
18   roberts 1987-01-04
19   douglas 1987-01-04
20     adams 1987-01-12
21    jensen 1987-01-15
22    murray 1987-01-16

### Задание 11
Выбрать фамилии всех сотрудников, которые поступили на работу в 1985 году.

In [194]:
pd.read_sql_query('''
  SELECT 
    last_name,
    hire_date
  FROM 
    Employee
  WHERE
    hire_date BETWEEN '1985-01-01' AND '1985-12-31'
  ORDER BY
    hire_date
''',conn)

last_name  hire_date
0      allen 1985-02-20
1       ward 1985-02-22
2     peters 1985-03-31
3       shaw 1985-04-02
4      jones 1985-04-02
5      doyle 1985-04-04
6       west 1985-04-04
7    alberts 1985-04-06
8     porter 1985-04-15
9      lewis 1985-04-16
10   sommers 1985-04-19
11     blake 1985-05-01
12    dennis 1985-05-15
13    duncan 1985-05-31
14     lange 1985-06-01
15      ross 1985-06-01
16     clark 1985-06-09
17     baker 1985-06-10
18    turner 1985-09-08
19    martin 1985-09-28
20      king 1985-11-17
21     james 1985-12-03
22      ford 1985-12-03

### Задание 12
Для каждого сотрудника выбрать количество полных лет работы в фирме.

In [195]:
pd.read_sql_query('''
  SELECT 
    first_name,
    last_name,
    2019 - YEAR(hire_date) AS 'Exp'
  FROM 
    Employee
  ORDER BY
    Exp DESC
''',conn)
#DATEDIFF(yy, hire_date, GETDATE()) -Наверное можно было бы элегантнее.

first_name last_name  Exp
0        john     smith   35
1       kevin     allen   34
2    jennifer      ford   34
3        fred     james   34
4        mary    turner   34
5     francis      king   34
6        paul      ross   34
7       livia      west   34
8       carol     clark   34
9      marion     blake   34
10     denise   sommers   34
11    kenneth    martin   34
12    richard     lewis   34
13      chris   alberts   34
14       jean     doyle   34
15       lynn    dennis   34
16     leslie     baker   34
17    cynthia      ward   34
18     daniel    peters   34
19      karen      shaw   34
20      sarah    duncan   34
21    gregory     lange   34
22      terry     jones   34
23    raymond    porter   34
24    matthew    fisher   33
25     donald     scott   33
26    barbara    miller   33
27      diane     adams   32
28      grace   roberts   32
29    michael   douglas   32
30      alice    jensen   32
31      james    murray   32

### Задание 13
Выбрать количество сотрудников, получающих комиссионные.

In [196]:
pd.read_sql_query('''
  SELECT 
    first_name,
    last_name,
    2019 - YEAR(hire_date) AS 'Exp'
  FROM 
    Employee
  ORDER BY
    Exp DESC
''',conn)

first_name last_name  Exp
0        john     smith   35
1       kevin     allen   34
2    jennifer      ford   34
3        fred     james   34
4        mary    turner   34
5     francis      king   34
6        paul      ross   34
7       livia      west   34
8       carol     clark   34
9      marion     blake   34
10     denise   sommers   34
11    kenneth    martin   34
12    richard     lewis   34
13      chris   alberts   34
14       jean     doyle   34
15       lynn    dennis   34
16     leslie     baker   34
17    cynthia      ward   34
18     daniel    peters   34
19      karen      shaw   34
20      sarah    duncan   34
21    gregory     lange   34
22      terry     jones   34
23    raymond    porter   34
24    matthew    fisher   33
25     donald     scott   33
26    barbara    miller   33
27      diane     adams   32
28      grace   roberts   32
29    michael   douglas   32
30      alice    jensen   32
31      james    murray   32

### Задание 14
Выбрать количество и общую сумму сделок, совершенных с покупателем, код которого - 104.

In [197]:
pd.read_sql_query('''
SELECT 
  customer_id, 
  SUM(total) AS 'Sum',
  COUNT(*) AS 'Count'
FROM 
  sales_order
WHERE
  customer_id LIKE '104'
GROUP BY 
  customer_id
''',conn)

customer_id     Sum  Count
0          104  7160.8      4

### Задание 15
Выбрать среднюю зарплату по каждой должности.

In [198]:
pd.read_sql_query('''
SELECT 
  job_id,
  AVG(salary) AS 'AVG'
FROM 
  Employee
GROUP BY
  job_id
''',conn)

job_id          AVG
0     667   921.428571
1     668  1825.000000
2     669  2968.750000
3     670  1331.818182
4     671  2725.000000
5     672  5000.000000

### Задание 16
Выбрать среднюю зарплата продавцов (код должности - 670).

In [199]:
pd.read_sql_query('''
SELECT 
  job_id,
  AVG(salary) AS 'AVG'
FROM 
  Employee
WHERE
  job_id = '670'
GROUP BY
  job_id
''',conn)

job_id          AVG
0     670  1331.818182

### Задание 17
 Выбрать средние зарплаты продавцов (код должности - 670) и клерков (код должности - 667).

In [200]:
pd.read_sql_query('''
SELECT 
  job_id,
  AVG(salary) AS 'AVG'
FROM 
  Employee
WHERE
  job_id = '670' OR job_id = '667'
GROUP BY
  job_id
''',conn)

job_id          AVG
0     667   921.428571
1     670  1331.818182

### Задание 18
Выбрать коды продуктов, по которым было совершено меньше 10 продаж.



In [201]:
pd.read_sql_query('''
SELECT DISTINCT
  item_id
FROM 
  item
WHERE
  quantity >= 10
''',conn)

item_id
0        1
1        2
2        3
3        4
4        5
5        6
6        7
7        8
8        9
9       10

### Задание 19
Выбрать максимальную зарплату продавцов (код должности - 670) по каждому отделу.

In [202]:
pd.read_sql_query('''
SELECT 
  department_id,
  MAX(salary) AS 'Max'
FROM 
  Employee
WHERE
  job_id = '670'
GROUP BY
  department_id
''',conn)

department_id     Max
0             13  1250.0
1             23  1500.0
2             30  1600.0
3             43  1300.0

### Задание 20
Выбрать список сотрудников фирмы в алфавитном порядке.

In [203]:
pd.read_sql_query('''
SELECT 
  last_name,
  first_name
FROM 
  Employee
ORDER BY
  last_name
''',conn)

last_name first_name
0      adams      diane
1    alberts      chris
2      allen      kevin
3      baker     leslie
4      blake     marion
5      clark      carol
6     dennis       lynn
7    douglas    michael
8      doyle       jean
9     duncan      sarah
10    fisher    matthew
11      ford   jennifer
12     james       fred
13    jensen      alice
14     jones      terry
15      king    francis
16     lange    gregory
17     lewis    richard
18    martin    kenneth
19    miller    barbara
20    murray      james
21    peters     daniel
22    porter    raymond
23   roberts      grace
24      ross       paul
25     scott     donald
26      shaw      karen
27     smith       john
28   sommers     denise
29    turner       mary
30      ward    cynthia
31      west      livia

In [204]:
pd.read_sql_query('''
SELECT 
  last_name,
  first_name
FROM 
  Employee
ORDER BY
  first_name
''',conn)

last_name first_name
0     jensen      alice
1     miller    barbara
2      clark      carol
3    alberts      chris
4       ward    cynthia
5     peters     daniel
6    sommers     denise
7      adams      diane
8      scott     donald
9       king    francis
10     james       fred
11   roberts      grace
12     lange    gregory
13    murray      james
14     doyle       jean
15      ford   jennifer
16     smith       john
17      shaw      karen
18    martin    kenneth
19     allen      kevin
20     baker     leslie
21      west      livia
22    dennis       lynn
23     blake     marion
24    turner       mary
25    fisher    matthew
26   douglas    michael
27      ross       paul
28    porter    raymond
29     lewis    richard
30    duncan      sarah
31     jones      terry